spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tolkienpets?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root          # <-- tu usuario MySQL
    password: rootpass      # <-- tu password MySQL
  jpa:
    hibernate:
      ddl-auto: update      # en producción, mejor 'validate' + migraciones (Flyway)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  h2:
#    console:
#      enabled: true        # <- puedes quitar H2; ya no se usa con MySQL

server:
  port: 8080

jwt:
  secret: change-me-super-secret-32chars-min
  expiration: 86400000
