server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: tolkien-virtual-pets-api

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.tolkien.pets: DEBUG   # 🔹 Muestra logs detallados solo de tu app
  pattern:
    console: "%d{HH:mm:ss} [%highlight(%-5level)] %cyan(%logger{36}) - %msg%n"
  file:
    name: logs/tolkien-app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

jwt:
  secret: mySuperSecretKeyThatIsConstant
  expiration: 86400000

auth:
  refresh:
    expiration-days: 7
