server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: tolkien-virtual-pets-api
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: mySuperSecretKeyThatIsConstant
  expiration: 86400000

auth:
  refresh:
    expiration-days: 7
