spring:
  datasource:
    url: jdbc:h2:mem:tolkien;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  h2.console.enabled: true
server.port: 8080
