spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tolkienCreatures}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:Arestom123!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # No modifica la estructura de tablas
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  web:
    cors:
      allowed-origins: "https://tu-dominio.com"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

jwt:
  secret: ${JWT_SECRET:mi_clave_super_secreta_para_firmar_tokens_123456789}
  expiration: ${JWT_EXPIRATION:86400000}
