server:
  port: 8080

spring:
  spring:
    application:
      name: Tolkien Virtual Pets API
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: ${JWT_SECRET:change-me-dev-very-long-secret-at-least-64-bytes--------------------------------}
  expiration-ms: ${JWT_EXPIRATION_MS:900000} # 15 min

auth:
  refresh:
    expiration-days: ${REFRESH_EXP_DAYS:7}
    cookie:
      name: ${REFRESH_COOKIE_NAME:refresh_token}
      path: /api/auth
      same-site: Lax
      secure: false
