spring:
  datasource:
    url: jdbc:h2:mem:tolkienpets;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

auth:
  refresh:
    cookie:
      same-site: Lax
      secure: false
