spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tolkienCreatures?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: pets_user
    password: Arestom123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # en producción te recomiendo 'validate'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: change-me-super-secret-32chars-min
  expiration: 86400000
